export enum GenresEnum {
	rock = 'rock',
	liric = 'liric',
	pop = 'pop',
	hipHop = 'hip-hop',
	electronic = 'electronic',
	jazz = 'jazz',
	classical = 'classical',
	blues = 'blues',
	reggae = 'reggae',
	folk = 'folk',
	punk = 'punk',
	metal = 'metal',
	latin = 'latin',
	alternative = 'alternative',
	funk = 'funk',
	soul = 'soul',
	rnb = 'rnb',
	country = 'country',
	fusion = 'fusion',
	experimental = 'experimental',
	industrial = 'industrial',
}
