import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/layout/sidebar/Sidebar'
import Header from '@/components/layout/header/Header'
import MainProvider from '@/providers/MainProvider'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased px-3 max-w-[80rem] mx-auto`}>
				<MainProvider>
					<Header />
					<div className='mt-17 flex gap-3 bg-background'>
						<div className='w-[20%] min-w-[11rem] max-sm:hidden'>
							<Sidebar />
						</div>
						<div className='w-full'>{children}</div>
					</div>
				</MainProvider>
			</body>
		</html>
	)
}
