import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/layout/sidebar/Sidebar'
import Header from '@/components/layout/header/Header'
import MainProvider from '@/providers/MainProvider'
import Genres from '@/components/layout/genres/Genres'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased px-3`}>
				<MainProvider>
					<Header />
					<div className='mt-17 flex gap-3 bg-background'>
						<div className='w-[15%]'>
							<Sidebar />
						</div>
						<div className='w-[85%]'>{children}</div>
						<div className='max-sm:hidden'>
							<Genres />
						</div>
					</div>
				</MainProvider>
			</body>
		</html>
	)
}
